server:
  port: 8080
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://user:8081"
              - "http://country:8082"
              - "http://game:8083"
              - "http://localhost:8080"
              - "http://localhost:4173"
              - "http://localhost:5173"
              - "http://159.65.52.6/"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "x-xsrf-token"
              - "X-Requested-With"
              - "XMLHttpRequest"
              - "Origin"
              - "Access-Control-Allow-Headers"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://user:8081
          predicates:
            - Path=/users/**
        - id: card-service
          uri: http://country:8082
          predicates:
            - Path=/country/**
        - id: game-service
          uri: http://game:8083
          predicates:
            - Path=/game/**
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 600000000
      refresh-token:
        expiration: 604800000
