name: pnpm Example Workflow

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
         

      - name: Install pnpm
        run: |
          npm install -g pnpm@8.14.0

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build
        run: |
          cd frontend
          pnpm run build
